package com.wlk.ideaplugin.soqlsupport.sobject.meta;

public enum FieldType {
    TEXT, NUMBER, DATE, DATETIME, BOOLEAN, ID, REFERENCE, PICKLIST, CURRENCY, PERCENT,
    PHONE, EMAIL, URL, ADDRESS, LOCATION, LONGTEXT, HTML, SUMMARY, ROLLUP_SUMMARY,
    LOOKUP, MASTER_DETAIL, AUTO_NUMBER, FORMULA, ENCRYPTED_TEXT, TIME, ANYTYPE
}
