{
    tokens=[
        SEMI=';'
        EQ='='
        LP='('
        RP=')'
        space='regexp:\s+'
        comment-'regecp://.*'
        number='regexp:\d+(\.\d*)\?'
        id='regexp:\p{Alpha}\w*'
        string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\")"
        op_1='+'
        op_2='-'
        op_3='*'
        op_4='/'
        op_5='!'
    ]
    name(".*expr")='expression'
    extends(".*expr")=expr
}


<AssignmentStatement> ::= Left + "="+ Right
<Left> ::= <identifier>
<Right> ::= <identifier>
<identifier> ::= <letter> (<letter> | <digit> | "_")*
<letter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "z"
<digit> ::= "0" | "1" | "2" | "3"| "4" | "5" | "6" | "7"| "8" | "9"